meta_product_name: "HerzCaspar WebApp"
meta_title: "HerzCaspar e.V. - Making a diffrence"
meta_description: "Enriching the extended hospital stay of young adults and teenagers"
meta_image: "caspar.png"
twitter_account: "@product_twitter_account"
